version: 2

models:
  - name: fct_orders
    description: "Fact table representing individual order transactions with associated menu details, pricing, and promotions."
    columns:
      - name: order_id
        description: "Unique identifier for the order."
        tests:
          - not_null

      - name: brand
        description: "Brand of the menu item ordered."
        tests:
          - not_null

      - name: name
        description: "Name of the menu item ordered."
        tests:
          - not_null

      - name: price
        description: "Price of the menu item at the time of the order."
        tests:
          - not_null

      - name: cogs
        description: "Cost of goods sold (COGS) for the menu item."
        tests:
          - not_null

      - name: quantity
        description: "Quantity of the menu item ordered."
        tests:
          - not_null

      - name: sales_date
        description: "Date when the order was placed."
        tests:
          - not_null

      - name: discount_rate
        description: "Discount rate applied to the order."
        tests:
          - not_null

      - name: max_discount
        description: "Maximum allowable discount for the order."
        tests:
          - not_null